name: Check package updates
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      log-level:
        description: "Log level"
        default: "info"

env:
  LOG_LEVEL: ${{ github.event.inputs.log-level }}
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_PLATFORM: github
  # RENOVATE_PLATFORM_COMMIT: true
  # RENOVATE_BOT_NAME: 'breq'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: renovate package versions
        uses: renovatebot/github-action@v43.0.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
